# zmodload zsh/zprof
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# https://varun.ch/posts/slow-nvm/
export NVM_LAZY_LOAD=true
source ~/.zprezto-contrib/zsh-nvm/zsh-nvm.plugin.zsh

# first try to find a suggestion from your history, but, if it can't find a match, will find a suggestion from the completion engine
export ZSH_AUTOSUGGEST_STRATEGY=(history completion)
# Set ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE to an integer value to disable autosuggestion for large buffers. The default is unset, which means that autosuggestion will be tried for any buffer size. Recommended value is 20. This can be useful when pasting large amount of text in the terminal, to avoid triggering autosuggestion for strings that are too long.
export ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20

### Fix slowness of pastes with zsh-syntax-highlighting.zsh
pasteinit() {
  OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
  zle -N self-insert url-quote-magic # I wonder if you'd need `.url-quote-magic`?
}

pastefinish() {
  zle -N self-insert $OLD_SELF_INSERT
}
zstyle :bracketed-paste-magic paste-init pasteinit 
zstyle :bracketed-paste-magic paste-finish pastefinish

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[k" up-line-or-beginning-search # Up
bindkey "^[j" down-line-or-beginning-search # Down
bindkey '^[l' autosuggest-accept 

unsetopt correct
unsetopt correctall
export DISABLE_CORRECTION="true"

# https://unix.stackexchange.com/questions/87062/how-to-display-the-name-of-the-current-virtualenv
function virtualenv_info {
    [ $VIRTUAL_ENV ] && echo '('`basename $VIRTUAL_ENV`') '
}


alias activ="source ./venv/bin/activate" 
alias vim="nvim" 
alias vi="nvim" 
alias vimv="source ./venv/bin/activate && nvim ."

# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
alias startPg='~/Documents/pgadmin4/pgadmin4env/bin/python ~/Documents/pgadmin4/pgadmin4env/lib/python3.10/site-packages/pgadmin4/pgAdmin4.py'

export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin 
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. 
export PATH="$PATH:/opt/nvim-linux64/bin" 
export PATH=$HOME/.local/bin:$PATH 
export MANPATH=$HOME/tools/ripgrep/doc/man:$MANPATH 
export FPATH=$HOME/tools/ripgrep/complete:$FPATH 
alias lg='lazygit'
alias ga='git add --verbose'
alias gl='git pull'
alias gc='git commit --verbose'
alias gst='git status'
alias gp='git push'
alias lh='ls -lah'
function md() {
  pandoc $1 -s -c ~/.local/share/pandoc/gruvbox-dark-medium.min.css -o /tmp/pandocRenderedStyledMD.html
  xdg-open /tmp/pandocRenderedStyledMD.html
}

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
eval "$(zoxide init zsh)"
#zprof
