# zmodload zsh/zprof
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# https://varun.ch/posts/slow-nvm/
export NVM_LAZY_LOAD=true
source ~/.zprezto-contrib/zsh-nvm/zsh-nvm.plugin.zsh

# first try to find a suggestion from your history, but, if it can't find a match, will find a suggestion from the completion engine
export ZSH_AUTOSUGGEST_STRATEGY=(history completion)
# Set ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE to an integer value to disable autosuggestion for large buffers. The default is unset, which means that autosuggestion will be tried for any buffer size. Recommended value is 20. This can be useful when pasting large amount of text in the terminal, to avoid triggering autosuggestion for strings that are too long.
export ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20

### Fix slowness of pastes with zsh-syntax-highlighting.zsh
pasteinit() {
  OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
  zle -N self-insert url-quote-magic # I wonder if you'd need `.url-quote-magic`?
}

pastefinish() {
  zle -N self-insert $OLD_SELF_INSERT
}
zstyle :bracketed-paste-magic paste-init pasteinit
zstyle :bracketed-paste-magic paste-finish pastefinish

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey -v
#if [[ -n "$NVIM" ]]; then
  #bindkey -v
#fi
bindkey "^[k" up-line-or-beginning-search # Up
bindkey "^[j" down-line-or-beginning-search # Down
bindkey "^[l" autosuggest-accept
bindkey "^R" history-incremental-search-backward
bindkey "^S" history-incremental-search-forward
bindkey -r '^[;'
bindkey -r '^[h'
bindkey "^H" backward-delete-char


unsetopt correct
unsetopt correctall
export DISABLE_CORRECTION="true"

# https://unix.stackexchange.com/questions/87062/how-to-display-the-name-of-the-current-virtualenv
function virtualenv_info {
    [ $VIRTUAL_ENV ] && echo '('`basename $VIRTUAL_ENV`') '
}

alias activ="source activ_env"
alias vim="activ && nvim"
alias vi="activ && nvim"
alias vimv="activ && nvim"

export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.
export PATH="$PATH:/opt/nvim-linux-x86_64/bin"
export PATH=$HOME/.local/bin:$PATH
export MANPATH=$HOME/tools/ripgrep/doc/man:$MANPATH
export FPATH=$HOME/tools/ripgrep/complete:$FPATH
export MANPAGER='nvim +Man!'
alias lg='lazygit'
alias ga='git add --verbose'
alias gl='git pull'
alias gc='git commit --verbose'
alias gst='git status'
alias gp='git push'
alias lh='ls -lah'
alias sudop='sudo env PATH=$PATH'
alias ip='ip -c'
alias bin='f(){ p=${2:-8}; printf "%0${p}d\n" "$(echo "obase=2;$1" | bc)"; }; f'
alias hex='printf "%#x\n"'
alias oct='printf "%#o\n"'
alias dec='printf "%d\n"'

source "$HOME/.cargo/env"
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
eval "$(zoxide init zsh)"
#zprof
